server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_learn?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: hotel
    password: 123321
    virtual-host: /hotel
  data:
    mongodb:
      #      uri: mongodb://root:root123@192.168.150.101:27017/leadnews-history
      host: 192.168.150.101
      port: 27017
      authentication-database: admin
      username: root
      password: root123
      database: hotel-history
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo